# Pandas Introduction (Series and Dataframes)

In [3]:
# Install python packages from notebook cell
# ! pip install pandas

In [4]:
# %%timeit
import numpy as np
# np.arange(900).reshape((9, 100))

In [1]:
import pandas as pd

# Series
#### like excel column

In [6]:
l = [1, 2, 3, 4, 5, 6]
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [7]:
s1 = pd.Series(l)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
pd.Series(arr)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [9]:
index = list('abcde')
index

['a', 'b', 'c', 'd', 'e']

In [10]:
s2=pd.Series(arr, index = index, name = 'demo') # index values can be changed from
s2

a    0
b    1
c    2
d    3
e    4
Name: demo, dtype: int64

In [11]:
s1[0], s1.loc[0]

(np.int64(1), np.int64(1))

In [12]:
s2[0], s2['a'], s2.loc['a'], s2.iloc[0] #iloc only numeric value

C:\Users\acer\AppData\Local\Temp\ipykernel_12844\3900987021.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s2[0], s2['a'], s2.loc['a'], s2.iloc[0] #iloc only numeric value

(np.int64(0), np.int64(0), np.int64(0), np.int64(0))

In [13]:
arr = np.arange(12).reshape((3, 2, 2))
arr

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [14]:
tp = np.transpose(arr, (1, 0, 2))
tp

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

In [15]:
tp.shape

(2, 3, 2)

In [16]:
tp = np.transpose(arr, (1, 2, 0)) # to change dimension or axis
tp

array([[[ 0,  4,  8],
        [ 1,  5,  9]],

       [[ 2,  6, 10],
        [ 3,  7, 11]]])

In [17]:
s2

a    0
b    1
c    2
d    3
e    4
Name: demo, dtype: int64

In [ ]:
# to add values to series like broadcasting, pandas used numpy internally
s2 + 1000

a    1000
b    1001
c    1002
d    1003
e    1004
Name: demo, dtype: int64

In [21]:
s2.describe()

count    5.000000
mean     2.000000
std      1.581139
min      0.000000
25%      1.000000
50%      2.000000
75%      3.000000
max      4.000000
Name: demo, dtype: float64

In [22]:
s2.info()

<class 'pandas.core.series.Series'>
Index: 5 entries, a to e
Series name: demo
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 252.0+ bytes

# DataFrame 
#### tabular structure like excel sheet

In [23]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [26]:
# number of elements and values hsould be equal to create data frame
d = {
    "age": [10, 12, 11, 16, 9, 10],
    # "height": [1.5, 1.6, 1.7, 1.8, 1.9]
    "height": [1.5, 1.6, 1.7, 1.8, 1.9, 1.5]
}
df = pd.DataFrame(d)
df

   age  height
0   10     1.5
1   12     1.6
2   11     1.7
3   16     1.8
4    9     1.9
5   10     1.5

In [ ]:
# shows value in individual column

l =[
    [10, 12, 11, 16, 9, 10],
    [1.5, 1.6, 1.7, 1.8, 1.9, 1.5]
]
df = pd.DataFrame(l)
df

      0     1     2     3    4     5
0  10.0  12.0  11.0  16.0  9.0  10.0
1   1.5   1.6   1.7   1.8  1.9   1.5

In [30]:
arr = np.array(l).T
df = pd.DataFrame(arr, columns=['age', 'height'])
df

    age  height
0  10.0     1.5
1  12.0     1.6
2  11.0     1.7
3  16.0     1.8
4   9.0     1.9
5  10.0     1.5

In [31]:
l =[
    [10, 1.5],
    [12, 1.6],
    [11, 1.7],
    [16, 1.8],
    [9, 1.9],
    [10, 1.5]
]

df = pd.DataFrame(l, columns = ['age', 'height'])
df

   age  height
0   10     1.5
1   12     1.6
2   11     1.7
3   16     1.8
4    9     1.9
5   10     1.5

In [32]:
# number of elements and values hsould be equal to create data frame
d = {
    "age": [10, 12, 11, 16, 9, 10],
    # "height": [1.5, 1.6, 1.7, 1.8, 1.9]
    "height": [1.5, 1.6, 1.7, 1.8, 1.9, 1.5]
}
df1= pd.DataFrame(d)
df1

   age  height
0   10     1.5
1   12     1.6
2   11     1.7
3   16     1.8
4    9     1.9
5   10     1.5

In [33]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
# number of elements and values hsould be equal to create data frame
d = {
    "age": np.arange(50, 60),
    "height": np.linspace(4, 5, 10)
}
df2 = pd.DataFrame(d)
df2

   age    height
0   50  4.000000
1   51  4.111111
2   52  4.222222
3   53  4.333333
4   54  4.444444
5   55  4.555556
6   56  4.666667
7   57  4.777778
8   58  4.888889
9   59  5.000000

In [41]:
pd.concat([df1, df2], axis=0, ignore_index=True) # ignore_space = true, shows continuos index value

    age    height
0    10  1.500000
1    12  1.600000
2    11  1.700000
3    16  1.800000
4     9  1.900000
5    10  1.500000
6    50  4.000000
7    51  4.111111
8    52  4.222222
9    53  4.333333
10   54  4.444444
11   55  4.555556
12   56  4.666667
13   57  4.777778
14   58  4.888889
15   59  5.000000

In [47]:
d1 = {
    'a': np.arange(5),
    'b': np.random.random(5)
}
d1

{'a': array([0, 1, 2, 3, 4]),
 'b': array([0.72713136, 0.66628973, 0.61828837, 0.35495661, 0.025553  ])}

In [56]:
d2 ={'c': np.linspace(10, 19, 5),
     'd': np.linspace(100, 1000, 5)}
d2

{'c': array([10.  , 12.25, 14.5 , 16.75, 19.  ]),
 'd': array([ 100.,  325.,  550.,  775., 1000.])}

In [61]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [53]:
df1.head(2) # shows 2 records

   a         b
0  0  0.355024
1  1  0.049044

In [52]:
df2.head(3)

       c     d
0  10.00  4.00
1  12.25  4.25
2  14.50  4.50

In [60]:
pd.concat([df1, df2], axis=1, ignore_index=True)

   0         1      2      3
0  0  0.727131  10.00    4.0
1  1  0.666290  12.25   28.0
2  2  0.618288  14.50   52.0
3  3  0.354957  16.75   76.0
4  4  0.025553  19.00  100.0

In [59]:
df1.columns, df2.columns

(Index(['a', 'b'], dtype='object'), Index(['c', 'd'], dtype='object'))

In [62]:
columns = [col for df in [df1, df2] for col in df.columns]
columns

['a', 'b', 'c', 'd']

In [ ]:
cols = []
for df in [df1, df2]:
    for col in df.columns:
        cols.append()
print(cols)

In [64]:
df_cat = pd.concat([df1, df2], axis=1, ignore_index=True)
df_cat

   0         1      2       3
0  0  0.727131  10.00   100.0
1  1  0.666290  12.25   325.0
2  2  0.618288  14.50   550.0
3  3  0.354957  16.75   775.0
4  4  0.025553  19.00  1000.0

In [ ]:
df_cat.rename(columns={0: 'age', 1:'height', 2:'place', 3:'grade'})

   age    height  place   grade
0    0  0.727131  10.00   100.0
1    1  0.666290  12.25   325.0
2    2  0.618288  14.50   550.0
3    3  0.354957  16.75   775.0
4    4  0.025553  19.00  1000.0

In [ ]:
# to update the old dataframe, use either of two below for inplace updation 
# df_cat = df_cat.rename(columns={0: 'age', 1:'height', 2:'place', 3:'grade'})
df_cat.rename(columns={0: 'age', 1:'height', 2:'place', 3:'grade'}, inplace=True)
df_cat

   age    height  place   grade
0    0  0.727131  10.00   100.0
1    1  0.666290  12.25   325.0
2    2  0.618288  14.50   550.0
3    3  0.354957  16.75   775.0
4    4  0.025553  19.00  1000.0

In [70]:
df_cat = df_cat.rename(columns={'place': 'roll_num'})
df_cat

   age    height  roll_num   grade
0    0  0.727131     10.00   100.0
1    1  0.666290     12.25   325.0
2    2  0.618288     14.50   550.0
3    3  0.354957     16.75   775.0
4    4  0.025553     19.00  1000.0

In [74]:
df = pd.DataFrame(
    np.array([1, 2, 3, np.nan, 100, np.nan, 5, 6]).T
)
df

       0
0    1.0
1    2.0
2    3.0
3    NaN
4  100.0
5    NaN
6    5.0
7    6.0

In [75]:
df[0].backfill()

C:\Users\acer\AppData\Local\Temp\ipykernel_12844\4133717333.py:1: FutureWarning: DataFrame.backfill/Series.backfill is deprecated. Use DataFrame.bfill/Series.bfill instead
  df[0].backfill()

0      1.0
1      2.0
2      3.0
3    100.0
4    100.0
5      5.0
6      5.0
7      6.0
Name: 0, dtype: float64

In [76]:
df[0].ffill()

0      1.0
1      2.0
2      3.0
3      3.0
4    100.0
5    100.0
6      5.0
7      6.0
Name: 0, dtype: float64

In [77]:
df_cat

   age    height  roll_num   grade
0    0  0.727131     10.00   100.0
1    1  0.666290     12.25   325.0
2    2  0.618288     14.50   550.0
3    3  0.354957     16.75   775.0
4    4  0.025553     19.00  1000.0

In [ ]:
# to access column # if only one [] gives series data type, only one feature can be accesses as its a series
type(df_cat['age'])

pandas.core.series.Series

In [ ]:
# can be confused as dot is also used for accessing method
df_cat.height

0    0.727131
1    0.666290
2    0.618288
3    0.354957
4    0.025553
Name: height, dtype: float64

In [91]:
# for multiple access, shows dataframes as datatype
df_cat[['age', 'height', 'grade']]

   age    height   grade
0    0  0.727131   100.0
1    1  0.666290   325.0
2    2  0.618288   550.0
3    3  0.354957   775.0
4    4  0.025553  1000.0