# Importing data from external source (csv, excel, json)

In [1]:
import pandas as pd

In [ ]:
# pd.read_ fuctions returning type is dataframe
df = pd.read_csv('./data/data1.csv')
df

   Unnamed: 0   name  age  height
0           0   Jams   32     109
1           1   John   35     121
2           2   Jane   41     136
3           3    Bob   20     170
4           4  Alice   23     112
5           5   Mike   47     158
6           6    Dan   23     165

- If column name is not provided in csv file, then first record will be treated as column names. To avoid this, we can use pandas read-csv function with header = None and names parameter to specify column names

In [ ]:
#if data does not have a column pass header none
df = pd.read_csv('./data/data1_1.csv', header = None)
df

   0      1   2    3
0  0   Jams  32  109
1  1   John  35  121
2  2   Jane  41  136
3  3    Bob  20  170
4  4  Alice  23  112
5  5   Mike  47  158
6  6    Dan  23  165

In [6]:

df = pd.read_csv(
    './data/data1_1.csv', 
    header = None, 
    # names = list('abcd') 
    names = ['sn', 'name', 'age', 'height']
)
df

   sn   name  age  height
0   0   Jams   32     109
1   1   John   35     121
2   2   Jane   41     136
3   3    Bob   20     170
4   4  Alice   23     112
5   5   Mike   47     158
6   6    Dan   23     165

In [9]:
#delimeter: that separates the values by commas or spaces etc
# read_csv default separator is comma
df2 = pd.read_csv('./data/data2.csv', sep= '\t')
df2

   Unnamed: 0   name  age  height
0           0   Jams   32     109
1           1   John   35     121
2           2   Jane   41     136
3           3    Bob   20     170
4           4  Alice   23     112
5           5   Mike   47     158
6           6    Dan   23     165

## In pandas
- axis=0 : row-wise operation
- axis=1 : column-wise operation

In [ ]:
# drop : removes column or wow data with axis 
# axis=1 represent column wise  and axis=0 represents row-wise, its opposite of numpy
df2.drop('Unnamed: 0', axis=1)

    name  age  height
0   Jams   32     109
1   John   35     121
2   Jane   41     136
3    Bob   20     170
4  Alice   23     112
5   Mike   47     158
6    Dan   23     165

- Install openpyxl dependency to read from excel

pip install openpyxl

In [ ]:
# \ : to add methods for long statements 
df3 = pd.read_excel('./data/data4.xlsx', sheet_name='Sheet1')\
    .drop('Unnamed: 0', axis=1) 
df3

    name  age  height
0   Jams   32     109
1   John   35     121
2   Jane   41     136
3    Bob   20     170
4  Alice   23     112
5   Mike   47     158
6    Dan   23     165

In [19]:

df4 = pd.read_excel('./data/data5.xlsx', sheet_name='Sheet1')
df4

    name  age  height
0   Jams   32     109
1   John   35     121
2   Jane   41     136
3    Bob   20     170
4  Alice   23     112
5   Mike   47     158
6    Dan   23     165

In [20]:
df5 = pd.read_json('./data/data6.json')
df5

    name  age  height
0   Jams   32     109
1   John   35     121
2   Jane   41     136
3    Bob   20     170
4  Alice   23     112
5   Mike   47     158
6    Dan   23     165

In [21]:
df6 = pd.read_json('./data/data7_7.json')
df6

   id   name
0   1  Alice
1   2    Bob

In [23]:
df7 = pd.read_json('./data/data7.json')
df7

   id   name                                            details
0   1  Alice  {'age': 30, 'address': {'city': 'New York', 'z...
1   2    Bob  {'age': 25, 'address': {'city': 'Los Angeles',...

In [27]:
import json
with open('./data/data7.json', 'r') as f:
    data = json.load(f)
data

[{'id': 1,
  'name': 'Alice',
  'details': {'age': 30, 'address': {'city': 'New York', 'zip': '10001'}}},
 {'id': 2,
  'name': 'Bob',
  'details': {'age': 25, 'address': {'city': 'Los Angeles', 'zip': '90001'}}}]

In [28]:
pd.json_normalize(data)

   id   name  details.age details.address.city details.address.zip
0   1  Alice           30             New York               10001
1   2    Bob           25          Los Angeles               90001

In [29]:
pd.json_normalize(data, sep='_')

   id   name  details_age details_address_city details_address_zip
0   1  Alice           30             New York               10001
1   2    Bob           25          Los Angeles               90001