# Handling Missing and Duplicate Data

### Handling Missing Data

In [7]:
datapath = 'E:\TECH-AXIS\ClassTech\Class1\data\organizations-10000.csv'

In [8]:
import pandas as pd

In [9]:
# head: provides top 5 values 
df = pd.read_csv(datapath)
df.head()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,NaN,522816eF8fdBE6d,Mckinney PLC,http://soto.com/,Sri Lanka,Synergized global system engine,1988,Dairy,3930
1,2.0,70C7FBD7e6Aa3Ea,Cunningham LLC,http://harding-duffy.com/,Namibia,Team-oriented fault-tolerant adapter,2018,Library,7871
2,3.0,428B397eA2d7290,Ruiz-Walls,http://www.atkins.biz/,Iran,Re-contextualized bifurcated moderator,2003,Hospital / Health Care,3095
3,4.0,9D234Ae8Cc51C1c,"Parrish, Osborne and Clarke",http://salazar.info/,British Indian Ocean Territory (Chagos Archipe...,Fully-configurable next generation concept,1989,Supermarkets,5422
4,5.0,6CDCcdE3D0b7b44,"Diaz, Robles and Haley",https://www.brooks-scott.net/,Botswana,Inverse intangible methodology,2013,Nanotechnology,3135

In [10]:
df.isna()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False

In [11]:
# tail : ptovides last 5 values
df.tail()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
9995,9996.0,2EE82AD1Cd045cd,"Neal, Day and Wang",https://carson.net/,San Marino,Team-oriented multimedia core,2013,Import / Export,6123
9996,9997.0,06f1568A2CaF04a,"Barrett, Rojas and Adkins",https://douglas-garza.com/,Turkmenistan,Cross-group dedicated methodology,2018,Human Resources / HR,9043
9997,9998.0,B4B92A44e0331Bc,Franklin-Ayala,http://www.torres.org/,Yemen,Polarized exuding orchestration,1983,Financial Services,8951
9998,9999.0,01D2539e270CEbd,Wolfe-Mckee,http://www.parks.com/,Togo,Balanced value-added ability,1975,Environmental Services,2505
9999,10000.0,0D3b7DcFA21d92d,Beck LLC,https://wagner-glover.com/,Georgia,Decentralized context-sensitive service-desk,2007,Wireless,4552

In [12]:
True + False + True # True = 1, False = 0

2

In [13]:
#sum = identify Nan values in each column
df.isna().sum()

Index                  1
Organization Id        0
Name                   0
Website                0
Country                0
Description            0
Founded                0
Industry               0
Number of employees    0
dtype: int64

In [14]:
type(df['Index']), type(df[['Index']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

#### filtering records with NaN values in particular column

In [15]:
condition = df['Index'].isna() == True
#return series we have selected only aparticular column

In [19]:
df[condition]['Index', 'Organization Id'] # provide in list to extract column

KeyError: ('Index', 'Organization Id')

In [ ]:
df['Index']=df['Index'].fillna(1.0) # hardcoded value should not be provided, just example
df

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1.0,522816eF8fdBE6d,Mckinney PLC,http://soto.com/,Sri Lanka,Synergized global system engine,1988,Dairy,3930
1,2.0,70C7FBD7e6Aa3Ea,Cunningham LLC,http://harding-duffy.com/,Namibia,Team-oriented fault-tolerant adapter,2018,Library,7871
2,3.0,428B397eA2d7290,Ruiz-Walls,http://www.atkins.biz/,Iran,Re-contextualized bifurcated moderator,2003,Hospital / Health Care,3095
3,4.0,9D234Ae8Cc51C1c,"Parrish, Osborne and Clarke",http://salazar.info/,British Indian Ocean Territory (Chagos Archipe...,Fully-configurable next generation concept,1989,Supermarkets,5422
4,5.0,6CDCcdE3D0b7b44,"Diaz, Robles and Haley",https://www.brooks-scott.net/,Botswana,Inverse intangible methodology,2013,Nanotechnology,3135
...,...,...,...,...,...,...,...,...,...
9995,9996.0,2EE82AD1Cd045cd,"Neal, Day and Wang",https://carson.net/,San Marino,Team-oriented multimedia core,2013,Import / Export,6123
9996,9997.0,06f1568A2CaF04a,"Barrett, Rojas and Adkins",https://douglas-garza.com/,Turkmenistan,Cross-group dedicated methodology,2018,Human Resources / HR,9043
9997,9998.0,B4B92A44e0331Bc,Franklin-Ayala,http://www.torres.org/,Yemen,Polarized exuding orchestration,1983,Financial Services,8951
9998,9999.0,01D2539e270CEbd,Wolfe-Mckee,http://www.parks.com/,Togo,Balanced value-added ability,1975,Environmental Services,2505
9999,10000.0,0D3b7DcFA21d92d,Beck LLC,https://wagner-glover.com/,Georgia,Decentralized context-sensitive service-desk,2007,Wireless,4552

In [20]:
df.columns

Index(['Index', 'Organization Id', 'Name', 'Website', 'Country', 'Description',
       'Founded', 'Industry', 'Number of employees'],
      dtype='object')

In [21]:
# df['Number of ']
df.index

RangeIndex(start=0, stop=10000, step=1)

In [24]:
import random
# random.randrange(1, 10)
#indices to replace nan
random.seed(42)
idx = random.choices(df.index, k=10)
idx

[6394, 250, 2750, 2232, 7364, 6766, 8921, 869, 4219, 297]

In [22]:
import numpy as np

In [23]:
arr = df['Number of employees'].to_numpy().astype('float')
arr, np.isnan(arr).sum()

(array([3930., 7871., 3095., ..., 8951., 2505., 4552.], shape=(10000,)),
 np.int64(0))

In [ ]:
# df['Number of employees'][idx] = np.nan
arr[idx] = np.nan

In [ ]:
np.isnan(arr).sum()

np.int64(10)

In [ ]:
df['Number of employees'] = arr

In [25]:
df.isna().sum()

Index                  1
Organization Id        0
Name                   0
Website                0
Country                0
Description            0
Founded                0
Industry               0
Number of employees    0
dtype: int64

In [26]:
mean = df['Number of employees'].mean()
median = df['Number of employees'].median()
mean, median

(np.float64(4961.321), np.float64(4894.0))

In [27]:
# replace or  fill nan values
df['Number of employees'] = df['Number of employees'].fillna(mean)
df.isna().sum()

Index                  1
Organization Id        0
Name                   0
Website                0
Country                0
Description            0
Founded                0
Industry               0
Number of employees    0
dtype: int64

In [28]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [29]:
df = df.drop_duplicates()

In [30]:
df.loc[0].to_frame()

                                                   0
Index                                            NaN
Organization Id                      522816eF8fdBE6d
Name                                    Mckinney PLC
Website                             http://soto.com/
Country                                    Sri Lanka
Description          Synergized global system engine
Founded                                         1988
Industry                                       Dairy
Number of employees                             3930

In [31]:
df.iloc[0]

Index                                              NaN
Organization Id                        522816eF8fdBE6d
Name                                      Mckinney PLC
Website                               http://soto.com/
Country                                      Sri Lanka
Description            Synergized global system engine
Founded                                           1988
Industry                                         Dairy
Number of employees                               3930
Name: 0, dtype: object

In [32]:
# l = [[1.0, '522816eF8fdBE6d', 'Mckinney PLC', 'http://soto.com/', 'Sri Lanka', 'Synergized global system engine', 1988, 'Dairy', 3930]]
l = [df.iloc[0].values]
df2 = pd.DataFrame(l, columns=df.columns)
df2

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,NaN,522816eF8fdBE6d,Mckinney PLC,http://soto.com/,Sri Lanka,Synergized global system engine,1988,Dairy,3930

In [36]:
df3 = pd.concat([df2, df], ignore_index=True)
df3

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,NaN,522816eF8fdBE6d,Mckinney PLC,http://soto.com/,Sri Lanka,Synergized global system engine,1988,Dairy,3930
1,NaN,522816eF8fdBE6d,Mckinney PLC,http://soto.com/,Sri Lanka,Synergized global system engine,1988,Dairy,3930
2,2.0,70C7FBD7e6Aa3Ea,Cunningham LLC,http://harding-duffy.com/,Namibia,Team-oriented fault-tolerant adapter,2018,Library,7871
3,3.0,428B397eA2d7290,Ruiz-Walls,http://www.atkins.biz/,Iran,Re-contextualized bifurcated moderator,2003,Hospital / Health Care,3095
4,4.0,9D234Ae8Cc51C1c,"Parrish, Osborne and Clarke",http://salazar.info/,British Indian Ocean Territory (Chagos Archipe...,Fully-configurable next generation concept,1989,Supermarkets,5422
...,...,...,...,...,...,...,...,...,...
9996,9996.0,2EE82AD1Cd045cd,"Neal, Day and Wang",https://carson.net/,San Marino,Team-oriented multimedia core,2013,Import / Export,6123
9997,9997.0,06f1568A2CaF04a,"Barrett, Rojas and Adkins",https://douglas-garza.com/,Turkmenistan,Cross-group dedicated methodology,2018,Human Resources / HR,9043
9998,9998.0,B4B92A44e0331Bc,Franklin-Ayala,http://www.torres.org/,Yemen,Polarized exuding orchestration,1983,Financial Services,8951
9999,9999.0,01D2539e270CEbd,Wolfe-Mckee,http://www.parks.com/,Togo,Balanced value-added ability,1975,Environmental Services,2505
10000,10000.0,0D3b7DcFA21d92d,Beck LLC,https://wagner-glover.com/,Georgia,Decentralized context-sensitive service-desk,2007,Wireless,4552

In [37]:
df3.duplicated()

0        False
1         True
2        False
3        False
4        False
         ...
9996     False
9997     False
9998     False
9999     False
10000    False
Length: 10001, dtype: bool

In [34]:
df3.duplicated(keep='last') # in default keep = 'first'

NameError: name 'df3' is not defined

In [33]:
df3[df3.duplicated(keep='last')]

NameError: name 'df3' is not defined

In [ ]:
# identify the number of duplicated data 
df3.duplicated(['Organization Id']).sum()

np.int64(0)

In [ ]:
#subset of column names
df3 = df3.drop_duplicates(['Organization Id'])
df3

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1.0,522816eF8fdBE6d,Mckinney PLC,http://soto.com/,Sri Lanka,Synergized global system engine,1988,Dairy,3930.0
2,2.0,70C7FBD7e6Aa3Ea,Cunningham LLC,http://harding-duffy.com/,Namibia,Team-oriented fault-tolerant adapter,2018,Library,7871.0
3,3.0,428B397eA2d7290,Ruiz-Walls,http://www.atkins.biz/,Iran,Re-contextualized bifurcated moderator,2003,Hospital / Health Care,3095.0
4,4.0,9D234Ae8Cc51C1c,"Parrish, Osborne and Clarke",http://salazar.info/,British Indian Ocean Territory (Chagos Archipe...,Fully-configurable next generation concept,1989,Supermarkets,5422.0
5,5.0,6CDCcdE3D0b7b44,"Diaz, Robles and Haley",https://www.brooks-scott.net/,Botswana,Inverse intangible methodology,2013,Nanotechnology,3135.0
...,...,...,...,...,...,...,...,...,...
9996,9996.0,2EE82AD1Cd045cd,"Neal, Day and Wang",https://carson.net/,San Marino,Team-oriented multimedia core,2013,Import / Export,6123.0
9997,9997.0,06f1568A2CaF04a,"Barrett, Rojas and Adkins",https://douglas-garza.com/,Turkmenistan,Cross-group dedicated methodology,2018,Human Resources / HR,9043.0
9998,9998.0,B4B92A44e0331Bc,Franklin-Ayala,http://www.torres.org/,Yemen,Polarized exuding orchestration,1983,Financial Services,8951.0
9999,9999.0,01D2539e270CEbd,Wolfe-Mckee,http://www.parks.com/,Togo,Balanced value-added ability,1975,Environmental Services,2505.0
10000,10000.0,0D3b7DcFA21d92d,Beck LLC,https://wagner-glover.com/,Georgia,Decentralized context-sensitive service-desk,2007,Wireless,4552.0