### Topic 1 : Introduction to Pandas - Series & DataFrames

Task 1: Create a Pandas Series from a Python list.

In [148]:
import pandas as pd
import numpy as np

In [149]:
l1 = [1, 2, 3, 4, 5 ,6]
s1 = pd.Series(l1)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

Task 2. Given a Series of student scores, write a function to find the mean,
maximum, and minimum scores.

In [150]:
student_score = [91, 20, 40, 45, 70, 95, 80, 87, 33, 65]
# scores = pd.Series(student_score)
# scores
def grade(student_score):
    scores = pd.Series(student_score)
    mean_score = scores.mean()
    max_score = scores.max()
    min_score = scores.min()
    return mean_score, max_score, min_score

mean, maximum, minimum = grade(student_score)
print(f"Mean: {mean}, Max: {maximum}, Min: {minimum}")

Mean: 62.6, Max: 95, Min: 20

Task 3. Convert a NumPy array into a Pandas Series and perform basic arithmetic
operations.

In [151]:
np_arr = np.arange(1, 10, 2)

series1 = pd.Series(np_arr)
print(f'Series:\n{series1}')

added_series = series1 + 6
print(f'Added Series:\n{added_series}')
subtracted_series = series1 - 5
print(f'Subtracted Series:\n{subtracted_series}')

Series:
0    1
1    3
2    5
3    7
4    9
dtype: int64
Added Series:
0     7
1     9
2    11
3    13
4    15
dtype: int64
Subtracted Series:
0   -4
1   -2
2    0
3    2
4    4
dtype: int64

Task 4. Create a DataFrame using a dictionary where the columns represent
student names, ages, and marks.

In [152]:
students = {
    'Names': ['Johnny', 'Lisa', 'Jennie', 'Jackson', 'Joseph', 'Rose', 'Harry'],
    'Age': [20, 21, 22, 23, 24, 26, 24],
    'Score': [85, 90, 78, 28, 50, 98, 65],
    'City': ['Ltp', 'Bkt', 'Ktm', 'Ltp', 'Pkr', 'Btl', 'Ktm']
}
df1 = pd.DataFrame(students)
print(f'DataFrame:\n{df1}')

DataFrame:
     Names  Age  Score City
0   Johnny   20     85  Ltp
1     Lisa   21     90  Bkt
2   Jennie   22     78  Ktm
3  Jackson   23     28  Ltp
4   Joseph   24     50  Pkr
5     Rose   26     98  Btl
6    Harry   24     65  Ktm

Task 5. Write code to get column names, data types, and basic statistics of a
DataFrame.

In [153]:
cols = df1.columns.to_list()
cols_type = df1.dtypes.to_list()
cold_info = df1.describe()
print(f'Columns:\n{cols}',
      f'\nColumns Type:\n{cols_type}',
      f'\nColumns Info:\n{cold_info}')

Columns:
['Names', 'Age', 'Score', 'City']
Columns Type:
[dtype('O'), dtype('int64'), dtype('int64'), dtype('O')]
Columns Info:
             Age      Score
count   7.000000   7.000000
mean   22.857143  70.571429
std     2.035401  24.697214
min    20.000000  28.000000
25%    21.500000  57.500000
50%    23.000000  78.000000
75%    24.000000  87.500000
max    26.000000  98.000000

Task 6. Convert a Series containing dates as strings into Datetime format and
extract the year, month, and day.

In [154]:
date_series = pd.Series(['2023-01-15', '2024-06-20', '2025-12-05'])
date_series = pd.to_datetime(date_series)
print(f'Date Series:\n{date_series}')
print(f'Year:\n{date_series.dt.year}',
      f'\nMonth:\n{date_series.dt.month}',
      f'\nDay:\n{date_series.dt.day}')

Date Series:
0   2023-01-15
1   2024-06-20
2   2025-12-05
dtype: datetime64[ns]
Year:
0    2023
1    2024
2    2025
dtype: int32
Month:
0     1
1     6
2    12
dtype: int32
Day:
0    15
1    20
2     5
dtype: int32

Task 7. Given a DataFrame, select and print the first three columns and the last
five rows.

In [155]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [25, 30, 35, 40, 45, 50],
    'Major': ['Math', 'Science', 'History', 'Art', 'IT', 'Physics'],
    'GPA': [3.5, 3.8, 3.2, 3.9, 3.6, 3.7],
    'Passout_Year': [2023, 2024, 2025, 2023, 2024, 2025],
    'Salary': [50000, 60000, 70000, 80000, 90000, 85000]
}

df2 = pd.DataFrame(data)
print(f'DataFrame:\n{df2}')

first_three_cols = df2.iloc[:, :3]
last_five_rows = df2.iloc[-5:]
print(f'First Three Columns:\n{first_three_cols}',
      f'\nLast Five Rows:\n{last_five_rows}')

DataFrame:
      Name  Age    Major  GPA  Passout_Year  Salary
0    Alice   25     Math  3.5          2023   50000
1      Bob   30  Science  3.8          2024   60000
2  Charlie   35  History  3.2          2025   70000
3    David   40      Art  3.9          2023   80000
4      Eva   45       IT  3.6          2024   90000
5    Frank   50  Physics  3.7          2025   85000
First Three Columns:
      Name  Age    Major
0    Alice   25     Math
1      Bob   30  Science
2  Charlie   35  History
3    David   40      Art
4      Eva   45       IT
5    Frank   50  Physics
Last Five Rows:
      Name  Age    Major  GPA  Passout_Year  Salary
1      Bob   30  Science  3.8          2024   60000
2  Charlie   35  History  3.2          2025   70000
3    David   40      Art  3.9          2023   80000
4      Eva   45       IT  3.6          2024   90000
5    Frank   50  Physics  3.7          2025   85000


Task 8. Add a new column to a DataFrame that is the sum of two existing
numeric columns.

In [156]:
subjects = {
    'Math': [85, 90, 78, 88, 92],
    'Science': [80, 85, 75, 90, 95],
}
subject_df = pd.DataFrame(subjects)
print(f'Subject DataFrame:\n{subject_df}') 
subject_df['Total'] = subject_df["Math"] + subject_df["Science"]
print(f'Sum Data:\n{subject_df}')

Subject DataFrame:
   Math  Science
0    85       80
1    90       85
2    78       75
3    88       90
4    92       95
Sum Data:
   Math  Science  Total
0    85       80    165
1    90       85    175
2    78       75    153
3    88       90    178
4    92       95    187

Task 9. Rename a column in a DataFrame and change the index labels.

In [157]:
subject2 = {
    'Math': [85, 90, 78, 88, 92],
    'Science': [80, 85, 75, 90, 95],
}
subject2_df = pd.DataFrame(subjects)
subject2_df = subject2_df.rename(columns={'Math': 'English'})
print(f'Renamed DataFrame:\n{subject2_df}')
subject2_df.index = ['A', 'B', 'C', 'D', 'E']
print(f'Updated Index:\n{subject2_df}')

Renamed DataFrame:
   English  Science
0       85       80
1       90       85
2       78       75
3       88       90
4       92       95
Updated Index:
   English  Science
A       85       80
B       90       85
C       78       75
D       88       90
E       92       95

Task 10. Convert a Pandas Series with categorical values into numerical labels
using `.astype()` or `.factorize()`.

In [158]:
colors = pd.Series(['Red', 'Green', 'Blue', 'Green', 'Red', 'Blue'])
print(f'Colors Series:\n{colors}')
# Convert to categorical data type
numeric_labels = colors.astype('category').cat.codes
print(f'Numeric Labels:\n{numeric_labels}')

# convert to numerical labels using factorize
labels, uniques = pd.factorize(colors)
print("Numerical Labels:", labels)
print("Unique Categories:", uniques)

Colors Series:
0      Red
1    Green
2     Blue
3    Green
4      Red
5     Blue
dtype: object
Numeric Labels:
0    2
1    1
2    0
3    1
4    2
5    0
dtype: int8
Numerical Labels: [0 1 2 1 0 2]
Unique Categories: Index(['Red', 'Green', 'Blue'], dtype='object')

Task 11. Drop a specific column and a specific row from a DataFrame.

In [159]:
data_new = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Kathmandu', 'Lalitpur', 'Bhaktapur']
}

df3 = pd.DataFrame(data_new)
df3 = df3.drop('City', axis=1)

df3 = df3.drop(1, axis=0)

print(f'DataFrame after dropping column and row:\n{df3}')

DataFrame after dropping column and row:
      Name  Age
0    Alice   25
2  Charlie   35

Task 12. Write a function that takes a DataFrame as input and returns the total
number of missing values per column.

In [160]:
def missingValues(df_data):
    total = df_data.isnull().sum()
    return total

data = {
    'Name': ['Alice', 'Bob', None, None, 'Eva'],
    'Age': [25, None, 35, 60, 45],
    'City': ['Kathmandu', 'Lalitpur', 'Bhaktapur', 'Karnali', 'Pokhara'],
}
df_data = pd.DataFrame(data)

missing_counts = missingValues(df_data)
print(missing_counts)

Name    2
Age     1
City    0
dtype: int64

### Topic 2 :Importing Data (CSV, Excel, JSON)

Task 1: Import a CSV file into a Pandas DataFrame and display the first 5 rows.

In [161]:
csv_df = pd.read_csv('../data/data1.csv')
csv_df.head()

   Unnamed: 0   name  age  height
0           0   Jams   32     109
1           1   John   35     121
2           2   Jane   41     136
3           3    Bob   20     170
4           4  Alice   23     112

Task 2: Read an Excel file into a Pandas DataFrame and print its column names.

In [162]:
excel_df = pd.read_excel('../data/data4.xlsx')
excel_df.columns

Index(['Unnamed: 0', 'name', 'age', 'height'], dtype='object')

Task 3: Load a JSON file into a Pandas DataFrame and print the first 3 rows.

In [163]:
json_df = pd.read_json('../data/data6.json')
json_df.head(3)

   name  age  height
0  Jams   32     109
1  John   35     121
2  Jane   41     136

Task 4: Read a CSV file but **only select specific columns**.

In [164]:
csv_df2 = pd.read_csv('../data/data2.csv', sep='\t', usecols=['age', 'height'])
csv_df2

   age  height
0   32     109
1   35     121
2   41     136
3   20     170
4   23     112
5   47     158
6   23     165

Task 5: Import a CSV file and set a specific column as the index.

In [165]:

csv_df3 = pd.read_csv('../data/sample.csv', sep = ',', index_col='Unnamed: 0')
csv_df3.index.name = 'index'

print(f"Columns in CSV: {csv_df3.columns}")
csv_df3

Columns in CSV: Index(['name', 'age', 'height'], dtype='object')

        name  age  height
index
0       Jams   32     109
1       John   35     121
2       Jane   41     136
3        Bob   20     170
4      Alice   23     112
5       Mike   47     158
6        Dan   23     165

Task 6: Load an Excel file that contains **multiple sheets** and extract data
from a specific sheet.

In [166]:
file_path = '../data/sample_multisheet.xlsx'

xls = pd.ExcelFile(file_path)
print("Available sheets:", xls.sheet_names)

df = pd.read_excel(xls, sheet_name='Sales')
print(df.head())

Available sheets: ['Sales', 'Employees', 'Products']
         Date Product  Amount
0  2024-01-01       A     100
1  2024-01-02       B     150
2  2024-01-03       C     200
3  2024-01-04       D     300
4  2024-01-05       A     230

Task 7: Read a large CSV file in chunks and process each chunk separately.

In [167]:

chunk_size = 1000

for chunk in pd.read_csv('../data/organizations-10000.csv', chunksize=chunk_size):
   print(chunk['Number of employees'].mean())

5052.692
4941.412
4932.084
4960.648
5086.161
5120.673
4921.475
4828.574
4852.744
4916.747

Task 8: Save a Pandas DataFrame as a CSV file **without the index column**.

In [168]:
sample_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Joseph'],
    'Age': [25, 30, 35]
})

sample_df.to_csv('../data/students.csv', index=False)


Task 9: Write a DataFrame into an Excel file with multiple sheets.

In [169]:
sheet_df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
sheet_df2 = pd.DataFrame({'City': ['Kathmandu', 'Lalitpur'], 'Population': [1000000, 500000]})

with pd.ExcelWriter('../data/multiple_sheets.xlsx') as writer:
    sheet_df1.to_excel(writer, sheet_name='People', index=False)
    sheet_df2.to_excel(writer, sheet_name='Cities', index=False)

Task 10: Convert a DataFrame into a JSON object and save it as a `.json` file.

In [170]:
j_df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Joseph'], 'Age': [25, 30, 34]})

j_df.to_json('../data/sample_json.json', orient='records', indent=4)

Task 11: Write code to handle encoding issues while reading a CSV file with
special characters.

In [171]:
df = pd.read_csv('../data/special_chars.csv', encoding='utf-8-sig')

print(df.head())

       Name      Country      Comment
0      José       España       ¡Hola!
1       Zoë  Netherlands  Goedemiddag
2  François       France       Ça va?
3    Müller      Germany    Guten Tag
4     Søren      Denmark         Hej!

Task 12: Read a CSV file from a URL and display summary statistics.

In [172]:
url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv' 
df = pd.read_csv(url)

print(df.describe())

            Index   Height(Inches)"   "Weight(Pounds)"
count  200.000000        200.000000         200.000000
mean   100.500000         67.949800         127.221950
std     57.879185          1.940363          11.960959
min      1.000000         63.430000          97.900000
25%     50.750000         66.522500         119.895000
50%    100.500000         67.935000         127.875000
75%    150.250000         69.202500         136.097500
max    200.000000         73.900000         158.960000


Task 13: Write code to detect missing values while reading a CSV file and replace
them with `NaN`.

In [173]:
missing_df = pd.read_csv('../data/missing_data.csv', na_values=['', 'NA'])

print(missing_df.isna())

print(missing_df)

    Name    Age   City
0  False  False  False
1  False   True  False
2  False   True  False
3  False   True  False
4  False  False   True
      Name   Age         City
0    Alice  25.0     New York
1      Bob   NaN  Los Angeles
2  Charlie   NaN      Chicago
3  Charlie   NaN      Chicago
4    David  30.0          NaN

Task 14: Load a CSV file, rename specific columns, and save it as a new CSV file.

In [174]:
st_df = pd.read_csv('../data/data2.csv', sep='\t')

st_df.rename(columns={
    'name': 'FirstName',
    'age': 'Years'
}, inplace=True)

st_df.to_csv('../data/new_data2.csv', index=False)

print(st_df)

   Unnamed: 0 FirstName  Years  height
0           0      Jams     32     109
1           1      John     35     121
2           2      Jane     41     136
3           3       Bob     20     170
4           4     Alice     23     112
5           5      Mike     47     158
6           6       Dan     23     165

### Topic 3 :Data Cleaning (Handling Missing & Duplicate Data)
Task 1: Create two NumPy arrays of shape (3,3) and add them using
broadcasting without using loops.

In [175]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[10], [20], [30]]) 

result = a + b
print(result)

[[11 12 13]
 [24 25 26]
 [37 38 39]]

Task 2. Load a dataset and check for missing values in each column.

In [176]:
missing_dataset = pd.read_csv('../data/missing_data.csv')
print(missing_dataset.isnull().sum())

Name    0
Age     3
City    1
dtype: int64

Task 3. Write code to replace all missing values in a DataFrame with `0`.

In [177]:
missing_dataset.fillna(0, inplace=True)
print(missing_dataset)

      Name   Age         City
0    Alice  25.0     New York
1      Bob   0.0  Los Angeles
2  Charlie   0.0      Chicago
3  Charlie   0.0      Chicago
4    David  30.0            0

Task 4. Remove rows that contain **NaN values** in any column.

In [178]:
missing_df.dropna(inplace=True)
print(missing_df)

    Name   Age      City
0  Alice  25.0  New York

Task 5. Replace missing values in a DataFrame with the mean, median, or mode
of that column.

In [179]:
missing_df2 = pd.read_csv('../data/missing_data2.csv')
print(missing_dataset.isnull().sum()) 
missing_df2['Age'] = missing_df2['Age'].fillna(missing_df2['Age'].median())

print(missing_df2)

Name    0
Age     0
City    0
dtype: int64
      Name   Age         City
0    Alice  25.0     New York
1      Bob  28.0  Los Angeles
2  Charlie  28.0      Chicago
3    David  30.0          NaN
4    David  30.0          NaN
5   Joshua  22.0        Texas
6     Lisa  28.0      Chicago


Task 6. Drop duplicate rows from a dataset while keeping the first occurrence.

In [180]:
missing_df2.drop_duplicates(keep='first', inplace=True)
print(missing_df2)

      Name   Age         City
0    Alice  25.0     New York
1      Bob  28.0  Los Angeles
2  Charlie  28.0      Chicago
3    David  30.0          NaN
5   Joshua  22.0        Texas
6     Lisa  28.0      Chicago


Task 7. Identify and remove duplicate rows based on a specific column/s.

In [181]:
missing_dataset.drop_duplicates(subset='City', keep='first', inplace=True)

print(missing_dataset)

      Name   Age         City
0    Alice  25.0     New York
1      Bob   0.0  Los Angeles
2  Charlie   0.0      Chicago
4    David  30.0            0

Task 8. Convert a column with incorrect data types (e.g., string instead of
integer) to the correct type.

In [182]:
missing_df2['Age'] = pd.to_numeric(missing_df2['Age'], errors='coerce')
print(missing_df2)

      Name   Age         City
0    Alice  25.0     New York
1      Bob  28.0  Los Angeles
2  Charlie  28.0      Chicago
3    David  30.0          NaN
5   Joshua  22.0        Texas
6     Lisa  28.0      Chicago

Task 9. Handle missing categorical values by replacing them with the most
frequent category.

In [183]:
missing_df2['City'] = missing_df2['City'].fillna(missing_df2['City'].mode()[0])
print(missing_df2)

      Name   Age         City
0    Alice  25.0     New York
1      Bob  28.0  Los Angeles
2  Charlie  28.0      Chicago
3    David  30.0      Chicago
5   Joshua  22.0        Texas
6     Lisa  28.0      Chicago

Task 10. Fill missing values using the forward-fill (`ffill`) and backward-fill (`bfill`)
methods.

In [184]:
none_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'David', 'Joshua', 'Lisa'],
    'Age': [25.0, None, None, 30.0, 30.0, 22.0, 28.0],
    'City': ['New York', 'Los Angeles', 'Chicago', None, None, 'Texas', 'Chicago']
}
none_df = pd.DataFrame(none_data)
df_ffill = none_df.fillna(method='ffill')

df_bfill = none_df.fillna(method='bfill')

print("Forward Fill:\n", df_ffill)
print("\nBackward Fill:\n", df_bfill)

Forward Fill:
       Name   Age         City
0    Alice  25.0     New York
1      Bob  25.0  Los Angeles
2  Charlie  25.0      Chicago
3    David  30.0      Chicago
4    David  30.0      Chicago
5   Joshua  22.0        Texas
6     Lisa  28.0      Chicago

Backward Fill:
       Name   Age         City
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  30.0      Chicago
3    David  30.0        Texas
4    David  30.0        Texas
5   Joshua  22.0        Texas
6     Lisa  28.0      Chicago

C:\Users\acer\AppData\Local\Temp\ipykernel_15376\2001897173.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = none_df.fillna(method='ffill')
C:\Users\acer\AppData\Local\Temp\ipykernel_15376\2001897173.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = none_df.fillna(method='bfill')

Task 11. Detect and replace outliers in a dataset using the IQR method.

In [185]:
Q1 = missing_df2['Age'].quantile(0.25)
Q3 = missing_df2['Age'].quantile(0.75)
IQR = Q3 - Q1

outlier_condition = (missing_df2['Age'] < (Q1 - 1.5 * IQR)) | (missing_df2['Age'] > (Q3 + 1.5 * IQR))
df_no_outliers = missing_df2[~outlier_condition]
print(df_no_outliers)

      Name   Age         City
0    Alice  25.0     New York
1      Bob  28.0  Los Angeles
2  Charlie  28.0      Chicago
3    David  30.0      Chicago
6     Lisa  28.0      Chicago


Task 12. Write code to standardize text data (convert to lowercase, remove
spaces, etc.).

In [186]:
df1['City'] = df1['City'].str.lower().str.strip()
print(df1)

     Names  Age  Score City
0   Johnny   20     85  ltp
1     Lisa   21     90  bkt
2   Jennie   22     78  ktm
3  Jackson   23     28  ltp
4   Joseph   24     50  pkr
5     Rose   26     98  btl
6    Harry   24     65  ktm


Task 13. Write a function that finds and removes columns that contain more than
50% missing values.

In [187]:
def remove_columns_with_missing(df1):
    threshold = len(df1) * 0.5
    df_cleaned = df1.dropna(axis=1, thresh=threshold)
    return df_cleaned

df_cleaned = remove_columns_with_missing(df1)
print(df_cleaned)

     Names  Age  Score City
0   Johnny   20     85  ltp
1     Lisa   21     90  bkt
2   Jennie   22     78  ktm
3  Jackson   23     28  ltp
4   Joseph   24     50  pkr
5     Rose   26     98  btl
6    Harry   24     65  ktm

Task 14. Identify and remove leading and trailing spaces in string columns.

In [188]:
df1['City'] = df1['City'].str.strip()
print(df1)

     Names  Age  Score City
0   Johnny   20     85  ltp
1     Lisa   21     90  bkt
2   Jennie   22     78  ktm
3  Jackson   23     28  ltp
4   Joseph   24     50  pkr
5     Rose   26     98  btl
6    Harry   24     65  ktm

### Topic 4 : Data Transformation (Sorting, Filtering, Applying Functions)
Task 1. Sort a DataFrame by multiple columns in ascending and descending
order.

In [189]:
df_sorted = df1.sort_values(by=['Age', 'Score'], ascending=[True, False])
print(df_sorted)

     Names  Age  Score City
0   Johnny   20     85  ltp
1     Lisa   21     90  bkt
2   Jennie   22     78  ktm
3  Jackson   23     28  ltp
6    Harry   24     65  ktm
4   Joseph   24     50  pkr
5     Rose   26     98  btl

Task 2. Filter a DataFrame to show only rows where a numeric column is greater
than a given threshold.

In [190]:
df_filtered = df1[df1['Score'] > 80]
print(df_filtered)

    Names  Age  Score City
0  Johnny   20     85  ltp
1    Lisa   21     90  bkt
5    Rose   26     98  btl

Task 3. Filter a DataFrame based on multiple conditions.

In [191]:
df_filtered_multiple = df1[(df1['Age'] > 22) & (df1['Score'] > 80)]
print(df_filtered_multiple)

  Names  Age  Score City
5  Rose   26     98  btl

Task 4. Select rows where a string column contains a specific keyword (e.g.,
"apple").

In [192]:
df_filtered_string = df1[df1['City'].str.contains('Kt', case=False)]
print(df_filtered_string)

    Names  Age  Score City
1    Lisa   21     90  bkt
2  Jennie   22     78  ktm
6   Harry   24     65  ktm


Task 5. Apply a function to modify all values in a column.

In [193]:
df1['Score'] = df1['Score'].apply(lambda x: x * 1.1)
print(df1)

     Names  Age  Score City
0   Johnny   20   93.5  ltp
1     Lisa   21   99.0  bkt
2   Jennie   22   85.8  ktm
3  Jackson   23   30.8  ltp
4   Joseph   24   55.0  pkr
5     Rose   26  107.8  btl
6    Harry   24   71.5  ktm

Task 6. Create a new column based on the conditions in another column (e.g.,
"Pass" or "Fail" based on marks).

In [194]:
df1['Result'] = df1['Score'].apply(lambda x: 'Pass' if x >= 50 else 'Fail')
print(df1)

     Names  Age  Score City Result
0   Johnny   20   93.5  ltp   Pass
1     Lisa   21   99.0  bkt   Pass
2   Jennie   22   85.8  ktm   Pass
3  Jackson   23   30.8  ltp   Fail
4   Joseph   24   55.0  pkr   Pass
5     Rose   26  107.8  btl   Pass
6    Harry   24   71.5  ktm   Pass

Task 7. Replace all negative values in a column with `0`.

In [195]:
df1['Score'] = df1['Score'].apply(lambda x: max(x, 0))
print(df1)

     Names  Age  Score City Result
0   Johnny   20   93.5  ltp   Pass
1     Lisa   21   99.0  bkt   Pass
2   Jennie   22   85.8  ktm   Pass
3  Jackson   23   30.8  ltp   Fail
4   Joseph   24   55.0  pkr   Pass
5     Rose   26  107.8  btl   Pass
6    Harry   24   71.5  ktm   Pass


Task 8. Normalize a column using Min-Max Scaling.

In [ ]:
df1['Age_Score_Difference'] = df1['Age'] - df1['Score']
print(df1)


Task 9. Use `.apply()` to apply a custom function row-wise.

In [ ]:
df_grouped = df1.groupby('City')['Score'].mean()
print(df_grouped)


Task 10. Create a new categorical column using `pd.cut()` to group numerical
data into bins.

In [ ]:
df_pivot = df1.pivot_table(values='Score', index='City', columns='Age', aggfunc='mean')
print(df_pivot)


Task 11. Find the top 5 highest and lowest values in a DataFrame.

In [ ]:
df1['Age'] = df1.apply(lambda row: row['Age'] + 1 if row['Score'] > 80 else row['Age'], axis=1)
print(df1)

Task 12. Rank values in a column and create a new column with the rankings.

In [ ]:
df1['Score'] = df1['Score'] / df1['Score'].max()
print(df1)

Task 13. Convert a categorical column into **dummy variables using
`pd.get_dummies()`.

In [ ]:
df1['Domain'] = df1['Email'].apply(lambda x: x.split('@')[1])
print(df1)

Task 14. Write a function to replace outliers in a DataFrame with the median of
the column.

In [ ]:
df_transformed = df1.groupby('City')['Score'].transform('mean')
print(df_transformed)

### Topic 5: Grouping & Aggregation in Pandas
Task 1. Group a dataset by a specific column and calculate the mean of another
column.






Task 2. Use `.groupby()` to count the occurrences of each unique value in a
column.
Task 3. Compute multiple aggregations (mean, max, min) for each group.
Task 4. Group data based on two columns and compute summary statistics.
Task 5. Use `.agg()` to apply different functions to different columns.
Task 6. Compute the cumulative sum and cumulative product for each group.
Task 7. Create a pivot table to summarize a DataFrame.
Task 8. Apply a custom aggregation function to each group.
Task 9. Write a function to filter the groups having more than 5 rows.
Task 10. Find the top 3 records from each group based on a specific column.
Task 11. Find the earliest and latest dates for each group in a time-series
dataset.
Task 12. Calculate the rolling average within each group.
Topic 6: Merging, Joining, and Concatenating DataFrames
Task 1. Explain the difference between **merge, join, and concatenate in Pandas.
Task 2. Merge two DataFrames based on a common column.
Task 3. Perform an **inner join** between two DataFrames.
Task 4. Perform a **left join** and explain when to use it.
Task 5. Perform an **outer join** and explain its use case.
Task 6. Concatenate two DataFrames **vertically (row-wise)**.
Task 7. Concatenate two DataFrames **horizontally (column-wise)**.
Task 8. Merge DataFrames with different column names (using `left_on` and
`right_on`).
Task 9. Use the '.join()` method to merge two DataFrames based on their index.
Task 10. Handle missing values by filling with `0` after merging two datasets.
Task 11. Find records that **exist in one DataFrame but not the other**.
© 2025, TechAxis Pvt. Ltd. All rights reserved.
This training material is a proprietary compilation of various resources. Unauthorized reproduction,
distribution, or modification in any form is strictly prohibited.
Task 12. Create a new DataFrame by stacking multiple smaller DataFrames.
Task 13. Write a function that takes a list of DataFrames and merges them all..