### Topic 1 : Introduction to Pandas - Series & DataFrames

Task 1: Create a Pandas Series from a Python list.

In [2]:
import pandas as pd
import numpy as np

In [3]:
l1 = [1, 2, 3, 4, 5 ,6]
s1 = pd.Series(l1)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

Task 2. Given a Series of student scores, write a function to find the mean,
maximum, and minimum scores.

In [4]:
student_score = [91, 20, 40, 45, 70, 95, 80, 87, 33, 65]
# scores = pd.Series(student_score)
# scores
def grade(student_score):
    scores = pd.Series(student_score)
    mean_score = scores.mean()
    max_score = scores.max()
    min_score = scores.min()
    return mean_score, max_score, min_score

grade(student_score)

(np.float64(62.6), np.int64(95), np.int64(20))

Task 3. Convert a NumPy array into a Pandas Series and perform basic arithmetic
operations.

In [5]:
np_arr = np.arange(1, 10, 2)

series1 = pd.Series(np_arr)
print(f'Series:\n{series1}')

added_series = series1 + 6
print(f'Added Series:\n{added_series}')
subtracted_series = series1 - 5
print(f'Subtracted Series:\n{subtracted_series}')

Series:
0    1
1    3
2    5
3    7
4    9
dtype: int64
Added Series:
0     7
1     9
2    11
3    13
4    15
dtype: int64
Subtracted Series:
0   -4
1   -2
2    0
3    2
4    4
dtype: int64

Task 4. Create a DataFrame using a dictionary where the columns represent
student names, ages, and marks.

In [6]:
students = {
    'Names': ['Johnny', 'Lisa', 'Jennie', 'Jackson', 'Joseph'],
    'Ages': [20, 21, 22, 23, 24],
    'Marks': [85, 90, 78, 88, 92]
}
df1 = pd.DataFrame(students)
print(f'DataFrame:\n{df1}')

DataFrame:
     Names  Ages  Marks
0   Johnny    20     85
1     Lisa    21     90
2   Jennie    22     78
3  Jackson    23     88
4   Joseph    24     92

Task 5. Write code to get column names, data types, and basic statistics of a
DataFrame.

In [7]:
cols = df1.columns.to_list()
cols_type = df1.dtypes.to_list()
cold_info = df1.describe()
print(f'Columns:\n{cols}',
      f'\nColumns Type:\n{cols_type}',
      f'\nColumns Info:\n{cold_info}')

Columns:
['Names', 'Ages', 'Marks']
Columns Type:
[dtype('O'), dtype('int64'), dtype('int64')]
Columns Info:
            Ages      Marks
count   5.000000   5.000000
mean   22.000000  86.600000
std     1.581139   5.458938
min    20.000000  78.000000
25%    21.000000  85.000000
50%    22.000000  88.000000
75%    23.000000  90.000000
max    24.000000  92.000000

Task 6. Convert a Series containing dates as strings into Datetime format and
extract the year, month, and day.

In [8]:
date_series = pd.Series(['2023-01-15', '2024-06-20', '2025-12-05'])
date_series = pd.to_datetime(date_series)
print(f'Date Series:\n{date_series}')
print(f'Year:\n{date_series.dt.year}',
      f'\nMonth:\n{date_series.dt.month}',
      f'\nDay:\n{date_series.dt.day}')

Date Series:
0   2023-01-15
1   2024-06-20
2   2025-12-05
dtype: datetime64[ns]
Year:
0    2023
1    2024
2    2025
dtype: int32
Month:
0     1
1     6
2    12
dtype: int32
Day:
0    15
1    20
2     5
dtype: int32

Task 7. Given a DataFrame, select and print the first three columns and the last
five rows.

In [9]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [25, 30, 35, 40, 45, 50],
    'Major': ['Math', 'Science', 'History', 'Art', 'IT', 'Physics'],
    'GPA': [3.5, 3.8, 3.2, 3.9, 3.6, 3.7],
    'Passout_Year': [2023, 2024, 2025, 2023, 2024, 2025],
    'Salary': [50000, 60000, 70000, 80000, 90000, 85000]
}

df2 = pd.DataFrame(data)
print(f'DataFrame:\n{df2}')

first_three_cols = df2.iloc[:, :3]
last_five_rows = df2.iloc[-5:]
print(f'First Three Columns:\n{first_three_cols}',
      f'\nLast Five Rows:\n{last_five_rows}')

DataFrame:
      Name  Age    Major  GPA  Passout_Year  Salary
0    Alice   25     Math  3.5          2023   50000
1      Bob   30  Science  3.8          2024   60000
2  Charlie   35  History  3.2          2025   70000
3    David   40      Art  3.9          2023   80000
4      Eva   45       IT  3.6          2024   90000
5    Frank   50  Physics  3.7          2025   85000
First Three Columns:
      Name  Age    Major
0    Alice   25     Math
1      Bob   30  Science
2  Charlie   35  History
3    David   40      Art
4      Eva   45       IT
5    Frank   50  Physics
Last Five Rows:
      Name  Age    Major  GPA  Passout_Year  Salary
1      Bob   30  Science  3.8          2024   60000
2  Charlie   35  History  3.2          2025   70000
3    David   40      Art  3.9          2023   80000
4      Eva   45       IT  3.6          2024   90000
5    Frank   50  Physics  3.7          2025   85000


Task 8. Add a new column to a DataFrame that is the sum of two existing
numeric columns.

In [10]:
subjects = {
    'Math': [85, 90, 78, 88, 92],
    'Science': [80, 85, 75, 90, 95],
}
subject_df = pd.DataFrame(subjects)
print(f'Subject DataFrame:\n{subject_df}') 
subject_df['Total'] = subject_df["Math"] + subject_df["Science"]
print(f'Sum Data:\n{subject_df}')

Subject DataFrame:
   Math  Science
0    85       80
1    90       85
2    78       75
3    88       90
4    92       95
Sum Data:
   Math  Science  Total
0    85       80    165
1    90       85    175
2    78       75    153
3    88       90    178
4    92       95    187

Task 9. Rename a column in a DataFrame and change the index labels.

In [11]:
subject2 = {
    'Math': [85, 90, 78, 88, 92],
    'Science': [80, 85, 75, 90, 95],
}
subject2_df = pd.DataFrame(subjects)
subject2_df = subject2_df.rename(columns={'Math': 'English'})
print(f'Renamed DataFrame:\n{subject2_df}')
subject2_df.index = ['A', 'B', 'C', 'D', 'E']
print(f'Updated Index:\n{subject2_df}')

Renamed DataFrame:
   English  Science
0       85       80
1       90       85
2       78       75
3       88       90
4       92       95
Updated Index:
   English  Science
A       85       80
B       90       85
C       78       75
D       88       90
E       92       95

Task 10. Convert a Pandas Series with categorical values into numerical labels
using `.astype()` or `.factorize()`.

In [12]:
colors = pd.Series(['Red', 'Green', 'Blue', 'Green', 'Red', 'Blue'])
print(f'Colors Series:\n{colors}')
# Convert to categorical data type
numeric_labels = colors.astype('category').cat.codes
print(f'Numeric Labels:\n{numeric_labels}')

# convert to numerical labels using factorize
labels, uniques = pd.factorize(colors)
print("Numerical Labels:", labels)
print("Unique Categories:", uniques)

Colors Series:
0      Red
1    Green
2     Blue
3    Green
4      Red
5     Blue
dtype: object
Numeric Labels:
0    2
1    1
2    0
3    1
4    2
5    0
dtype: int8
Numerical Labels: [0 1 2 1 0 2]
Unique Categories: Index(['Red', 'Green', 'Blue'], dtype='object')

Task 11. Drop a specific column and a specific row from a DataFrame.

In [13]:
data_new = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Kathmandu', 'Lalitpur', 'Bhaktapur']
}

df3 = pd.DataFrame(data_new)
df3 = df3.drop('City', axis=1)

df3 = df3.drop(1, axis=0)

print(f'DataFrame after dropping column and row:\n{df3}')

DataFrame after dropping column and row:
      Name  Age
0    Alice   25
2  Charlie   35

Task 12. Write a function that takes a DataFrame as input and returns the total
number of missing values per column.

In [14]:
def missingValues(df_data):
    total = df_data.isnull().sum()
    return total

data = {
    'Name': ['Alice', 'Bob', None, None, 'Eva'],
    'Age': [25, None, 35, 60, 45],
    'City': ['Kathmandu', 'Lalitpur', 'Bhaktapur', 'Karnali', 'Pokhara'],
}
df_data = pd.DataFrame(data)

missing_counts = missingValues(df_data)
print(missing_counts)

Name    2
Age     1
City    0
dtype: int64

### Topic 2 :Importing Data (CSV, Excel, JSON)

Task 1: Import a CSV file into a Pandas DataFrame and display the first 5 rows.

In [15]:
csv_df = pd.read_csv('../data/data1.csv')
csv_df.head()

   Unnamed: 0   name  age  height
0           0   Jams   32     109
1           1   John   35     121
2           2   Jane   41     136
3           3    Bob   20     170
4           4  Alice   23     112

Task 2: Read an Excel file into a Pandas DataFrame and print its column names.

In [16]:
excel_df = pd.read_excel('../data/data4.xlsx')
excel_df.columns

Index(['Unnamed: 0', 'name', 'age', 'height'], dtype='object')

Task 3: Load a JSON file into a Pandas DataFrame and print the first 3 rows.

In [17]:
json_df = pd.read_json('../data/data6.json')
json_df.head(3)

   name  age  height
0  Jams   32     109
1  John   35     121
2  Jane   41     136

Task 4: Read a CSV file but **only select specific columns**.

In [25]:
csv_df2 = pd.read_csv('../data/data2.csv', sep='\t', usecols=['age', 'height'])
csv_df2

   age  height
0   32     109
1   35     121
2   41     136
3   20     170
4   23     112
5   47     158
6   23     165

Task 5: Import a CSV file and set a specific column as the index.






Task 6: Load an Excel file that contains **multiple sheets** and extract data
from a specific sheet.
Task 7: Read a large CSV file in chunks and process each chunk separately.
Task 8: Save a Pandas DataFrame as a CSV file **without the index column**.
Task 9: Write a DataFrame into an Excel file with multiple sheets.
Task 10: Convert a DataFrame into a JSON object and save it as a `.json` file.
Task 11: Write code to handle encoding issues while reading a CSV file with
special characters.
Task 12: Read a CSV file from a URL and display summary statistics.
© 2025, TechAxis Pvt. Ltd. All rights reserved.
This training material is a proprietary compilation of various resources. Unauthorized reproduction,
distribution, or modification in any form is strictly prohibited.
Task 13: Write code to detect missing values while reading a CSV file and replace
them with `NaN`.
Task 14: Load a CSV file, rename specific columns, and save it as a new CSV file.
Topic 3 :Data Cleaning (Handling Missing & Duplicate Data)
Task 1: Create two NumPy arrays of shape (3,3) and add them using
broadcasting without using loops.
Task 2. Load a dataset and check for missing values in each column.
Task 3. Write code to replace all missing values in a DataFrame with `0`.
Task 4. Remove rows that contain **NaN values** in any column.
Task 5. Replace missing values in a DataFrame with the mean, median, or mode
of that column.
Task 6. Drop duplicate rows from a dataset while keeping the first occurrence.
Task 7. Identify and remove duplicate rows based on a specific column/s.
Task 8. Convert a column with incorrect data types (e.g., string instead of
integer) to the correct type.
Task 9. Handle missing categorical values by replacing them with the most
frequent category.
Task 10. Fill missing values using the forward-fill (`ffill`) and backward-fill (`bfill`)
methods.
Task 11. Detect and replace outliers in a dataset using the IQR method.
Task 12. Write code to standardize text data (convert to lowercase, remove
spaces, etc.).
Task 13. Write a function that finds and removes columns that contain more than
50% missing values.
Task 14. Identify and remove leading and trailing spaces in string columns.
Topic 4 : Data Transformation (Sorting, Filtering, Applying Functions)
Task 1. Sort a DataFrame by multiple columns in ascending and descending
order.
Task 2. Filter a DataFrame to show only rows where a numeric column is greater
than a given threshold.
Task 3. Filter a DataFrame based on multiple conditions.
Task 4. Select rows where a string column contains a specific keyword (e.g.,
"apple").
Task 5. Apply a function to modify all values in a column.
Task 6. Create a new column based on the conditions in another column (e.g.,
"Pass" or "Fail" based on marks).
Task 7. Replace all negative values in a column with `0`.
Task 8. Normalize a column using Min-Max Scaling.
© 2025, TechAxis Pvt. Ltd. All rights reserved.
This training material is a proprietary compilation of various resources. Unauthorized reproduction,
distribution, or modification in any form is strictly prohibited.
Task 9. Use `.apply()` to apply a custom function row-wise.
Task 10. Create a new categorical column using `pd.cut()` to group numerical
data into bins.
Task 11. Find the top 5 highest and lowest values in a DataFrame.
Task 12. Rank values in a column and create a new column with the rankings.
Task 13. Convert a categorical column into **dummy variables using
`pd.get_dummies()`.
Task 14. Write a function to replace outliers in a DataFrame with the median of
the column.
Topic 5: Grouping & Aggregation in Pandas
Task 1. Group a dataset by a specific column and calculate the mean of another
column.
Task 2. Use `.groupby()` to count the occurrences of each unique value in a
column.
Task 3. Compute multiple aggregations (mean, max, min) for each group.
Task 4. Group data based on two columns and compute summary statistics.
Task 5. Use `.agg()` to apply different functions to different columns.
Task 6. Compute the cumulative sum and cumulative product for each group.
Task 7. Create a pivot table to summarize a DataFrame.
Task 8. Apply a custom aggregation function to each group.
Task 9. Write a function to filter the groups having more than 5 rows.
Task 10. Find the top 3 records from each group based on a specific column.
Task 11. Find the earliest and latest dates for each group in a time-series
dataset.
Task 12. Calculate the rolling average within each group.
Topic 6: Merging, Joining, and Concatenating DataFrames
Task 1. Explain the difference between **merge, join, and concatenate in Pandas.
Task 2. Merge two DataFrames based on a common column.
Task 3. Perform an **inner join** between two DataFrames.
Task 4. Perform a **left join** and explain when to use it.
Task 5. Perform an **outer join** and explain its use case.
Task 6. Concatenate two DataFrames **vertically (row-wise)**.
Task 7. Concatenate two DataFrames **horizontally (column-wise)**.
Task 8. Merge DataFrames with different column names (using `left_on` and
`right_on`).
Task 9. Use the '.join()` method to merge two DataFrames based on their index.
Task 10. Handle missing values by filling with `0` after merging two datasets.
Task 11. Find records that **exist in one DataFrame but not the other**.
© 2025, TechAxis Pvt. Ltd. All rights reserved.
This training material is a proprietary compilation of various resources. Unauthorized reproduction,
distribution, or modification in any form is strictly prohibited.
Task 12. Create a new DataFrame by stacking multiple smaller DataFrames.
Task 13. Write a function that takes a list of DataFrames and merges them all..